const Workflow = require('../models/Workflow');
const WorkflowLog = require('../models/WorkflowLog');
const Task = require('../models/Task');
const Lead = require('../models/Lead');
const Customer = require('../models/Customer');
const Ticket = require('../models/Ticket');
const { getTenantFilter, getTenantId } = require('../utils/tenantScope');

// Helper to simulate workflow step execution
const executeWorkflowStep = async (step, entityType, entityId, tenantId) => {
  const { type, config } = step;
  const execution = { stepType: type, actionType: config.actionType, success: true, error: null };

  try {
    if (type === 'Delay') {
      console.log(`Delaying workflow step for ${config.delayDuration} ${config.delayUnit}`);
    } else if (type === 'Condition') {
      let entity;
      if (entityType === 'Lead') entity = await Lead.findOne({ _id: entityId, tenant: tenantId });
      else if (entityType === 'Customer') entity = await Customer.findOne({ _id: entityId, tenant: tenantId });
      else if (entityType === 'Ticket') entity = await Ticket.findOne({ _id: entityId, tenant: tenantId });

      if (!entity) {
        throw new Error(`${entityType} entity not found for condition evaluation`);
      }

      const fieldValue = entity[config.conditionField];
      const matchValue = config.conditionValue;
      let matched = false;

      switch (config.conditionOperator) {
        case 'equals':
          matched = String(fieldValue) === String(matchValue);
          break;
        case 'not_equals':
          matched = String(fieldValue) !== String(matchValue);
          break;
        case 'contains':
          matched = String(fieldValue).toLowerCase().includes(String(matchValue).toLowerCase());
          break;
        default:
          matched = false;
      }

      if (!matched) {
        execution.success = false;
        execution.error = `Condition field '${config.conditionField}' [${fieldValue}] does not match [${matchValue}]`;
      }
    } else if (type === 'Action') {
      switch (config.actionType) {
        case 'Create Task':
        case 'Create Retention Task':
          await Task.create({
            title: config.taskTitle || 'Automated Customer Retention Task',
            description: `Auto-generated by workflow execution for ${entityType} [${entityId}]`,
            priority: config.taskPriority || 'High',
            status: 'Pending',
            customer: entityType === 'Customer' ? entityId : undefined,
            tenant: tenantId,
          });
          break;

        case 'Notify Account Owner':
        case 'Notify Manager':
          console.log(`[Workflow Notification] Notifying owner/manager for ${entityType}: ${entityId}`);
          break;

        case 'Send Email':
        case 'Send Direct Marketing Email':
        case 'Enroll in Marketing Campaign': {
          let recipientObj;
          if (entityType === 'Lead') recipientObj = await Lead.findOne({ _id: entityId, tenant: tenantId });
          else if (entityType === 'Customer') recipientObj = await Customer.findOne({ _id: entityId, tenant: tenantId });

          if (recipientObj && recipientObj.email) {
            const recipientEmail = recipientObj.email.trim().toLowerCase();

            // Check unsubscribe status before sending
            const MarketingSubscription = require('../models/MarketingSubscription');
            const isUnsubscribed = await MarketingSubscription.findOne({ tenant: tenantId, email: recipientEmail, status: 'unsubscribed' });

            if (isUnsubscribed) {
              console.log(`[Workflow Marketing] Recipient ${recipientEmail} is unsubscribed. Skipping marketing action.`);
              execution.details = `Marketing email skipped for ${recipientEmail}: Recipient is unsubscribed (suppression_reason: marketing_unsubscribed).`;
              execution.suppressed = true;
              execution.suppressionReason = 'marketing_unsubscribed';
            } else {
              const { getWorkspaceIdentity } = require('../utils/tenantScope');
              const { sendOutboundEmail } = require('../services/invoice-email.service');
              const identity = await getWorkspaceIdentity(tenantId);

              const subject = config.emailSubject || `Special Update for ${recipientObj.contactName || recipientObj.contactPerson || 'you'}`;
              const body = config.emailBody || `<p>Hi ${recipientObj.contactName || recipientObj.contactPerson || 'there'},</p><p>We wanted to share an update regarding your relationship with ${identity.communicationEmailName || 'our team'}.</p>`;

              await sendOutboundEmail({
                to: recipientEmail,
                subject,
                html: body,
                fromName: identity.communicationEmailName,
                fromEmail: identity.communicationEmail,
              });

              if (entityType === 'Lead') {
                recipientObj.activityLog.push({
                  type: 'System',
                  description: `Workflow Triggered Email Sent: "${subject}"`,
                });
                await recipientObj.save();
              } else if (entityType === 'Customer') {
                recipientObj.activities.push({
                  type: 'Email',
                  description: `Workflow Triggered Email Sent: "${subject}"`,
                });
                await recipientObj.save();
              }
              console.log(`[Workflow Marketing] Successfully delivered automated email to ${recipientEmail}`);
            }
          }
          break;
        }

        case 'Send SMS':
        case 'Send WhatsApp Message':
          console.log(`[Workflow Outbound] Sending ${config.actionType} to entity: ${entityId}`);
          break;

        case 'Create Ticket':
          await Ticket.create({
            title: config.ticketTitle || 'Automated Support Ticket',
            description: `Generated automatically via workflow rule. Entity: ${entityType} (${entityId})`,
            priority: config.priority || 'Medium',
            status: 'Open',
            customer: entityType === 'Customer' ? entityId : undefined,
            lead: entityType === 'Lead' ? entityId : undefined,
            tenant: tenantId,
          });
          break;

        case 'Assign Ticket':
          if (entityType === 'Ticket') {
            const ticket = await Ticket.findOne({ _id: entityId, tenant: tenantId });
            if (ticket && config.assignedEmployee) {
              ticket.assignedEmployee = config.assignedEmployee;
              if (ticket.status === 'Open') ticket.status = 'Assigned';
              await ticket.save();
            }
          }
          break;

        case 'Change Priority':
          if (entityType === 'Ticket') {
            const ticket = await Ticket.findOne({ _id: entityId, tenant: tenantId });
            if (ticket && config.priority) {
              ticket.priority = config.priority;
              ticket.priorityExplanation = `Priority changed to ${config.priority} via automated workflow rule.`;
              ticket.priorityDrivers = [`Automated workflow action`];
              await ticket.save();
            }
          }
          break;

        case 'Change Ticket Status':
          if (entityType === 'Ticket') {
            const ticket = await Ticket.findOne({ _id: entityId, tenant: tenantId });
            if (ticket && config.ticketStatus) {
              ticket.status = config.ticketStatus;
              await ticket.save();
            }
          }
          break;

        case 'Add Internal Note':
          if (entityType === 'Ticket') {
            const ticket = await Ticket.findOne({ _id: entityId, tenant: tenantId });
            if (ticket && config.noteContent) {
              ticket.comments.push({
                comment: config.noteContent,
                commentedBy: config.user || ticket.tenant,
                isInternal: true,
                createdAt: new Date(),
              });
              await ticket.save();
            }
          }
          break;

        case 'Notify Workspace User':
          console.log(`[Workflow Notification] Notifying workspace user for ${entityType}: ${entityId}`);
          break;

        default:
          console.log(`Executing workflow action: ${config.actionType}`);
      }
    }
  } catch (err) {
    execution.success = false;
    execution.error = err.message;
  }

  return execution;
};

// Execute workflow triggers
const triggerWorkflowEvents = async (triggerName, entityType, entityId, tenantId) => {
  try {
    const workflows = await Workflow.find({ trigger: triggerName, isActive: true, tenant: tenantId });
    for (const workflow of workflows) {
      const log = await WorkflowLog.create({
        workflow: workflow._id,
        entityType,
        entityId,
        status: 'in_progress',
        executedSteps: [],
        tenant: tenantId,
      });

      let allPassed = true;
      const stepResults = [];

      for (let i = 0; i < workflow.steps.length; i++) {
        const step = workflow.steps[i];
        const res = await executeWorkflowStep(step, entityType, entityId, tenantId);
        res.stepIndex = i;
        stepResults.push(res);

        if (!res.success && step.type === 'Condition') {
          allPassed = false;
          break;
        }
      }

      log.executedSteps = stepResults;
      log.status = allPassed ? 'success' : 'failed';
      if (!allPassed) {
        log.errorDetails = stepResults[stepResults.length - 1].error || 'Workflow execution aborted at condition split';
      }
      await log.save();
    }
  } catch (err) {
    console.error('Workflow trigger err:', err.message);
  }
};

const getWorkflows = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const tenantId = getTenantId(req);
    let workflows = await Workflow.find(tenantFilter).sort({ createdAt: -1 });

    // Seed default workspace workflows if none exist for this tenant
    if (workflows.length === 0) {
      const defaultWorkflows = [
        {
          name: 'New Lead Onboarding Protocol',
          trigger: 'Lead Created',
          steps: [
            { type: 'Action', config: { actionType: 'Send Direct Marketing Email', emailSubject: 'Welcome to our platform!', emailBody: '<p>Hi there, thank you for reaching out.</p>' } },
            { type: 'Delay', config: { delayDuration: 2, delayUnit: 'days' } },
            { type: 'Action', config: { actionType: 'Create Task', taskTitle: 'Follow up on new lead onboarding', taskPriority: 'High' } },
          ],
          isActive: true,
          tenant: tenantId,
        },
        {
          name: 'Automated Customer Retention Protocol',
          trigger: 'Customer Becomes At Risk',
          steps: [
            { type: 'Action', config: { actionType: 'Create Retention Task', taskTitle: 'Review customer health drop', taskPriority: 'High' } },
            { type: 'Action', config: { actionType: 'Notify Account Owner' } },
          ],
          isActive: true,
          tenant: tenantId,
        },
        {
          name: 'Support Escalation Protocol',
          trigger: 'Ticket Created',
          steps: [
            { type: 'Action', config: { actionType: 'Assign Ticket' } },
            { type: 'Action', config: { actionType: 'Notify Manager' } },
          ],
          isActive: true,
          tenant: tenantId,
        },
      ];

      workflows = await Workflow.insertMany(defaultWorkflows);
    }

    res.json({ success: true, count: workflows.length, data: workflows });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const createWorkflow = async (req, res) => {
  try {
    const tenantId = getTenantId(req);
    const { name, trigger, steps } = req.body;
    const workflow = await Workflow.create({
      name,
      trigger,
      steps,
      tenant: tenantId,
    });
    res.status(201).json({ success: true, data: workflow });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const updateWorkflow = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const updateData = { ...req.body };
    delete updateData.tenant;

    const workflow = await Workflow.findOneAndUpdate(
      { _id: req.params.id, ...tenantFilter },
      updateData,
      { new: true, runValidators: true }
    );
    if (!workflow) {
      return res.status(404).json({ success: false, error: 'Workflow not found' });
    }
    res.json({ success: true, data: workflow });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const deleteWorkflow = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const workflow = await Workflow.findOneAndDelete({ _id: req.params.id, ...tenantFilter });
    if (!workflow) {
      return res.status(404).json({ success: false, error: 'Workflow not found' });
    }
    res.json({ success: true, message: 'Workflow deleted successfully' });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const getWorkflowLogs = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const logs = await WorkflowLog.find(tenantFilter)
      .populate('workflow', 'name trigger')
      .sort({ createdAt: -1 });
    res.json({ success: true, count: logs.length, data: logs });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const CAPABILITY_REGISTRY = {
  triggers: [
    { key: 'Lead Created', label: 'Lead Created', entityType: 'Lead', category: 'Leads' },
    { key: 'Lead Stage Changed', label: 'Lead Stage Changed', entityType: 'Lead', category: 'Leads' },
    { key: 'Lead Converted', label: 'Lead Converted to Customer', entityType: 'Lead', category: 'Leads' },
    { key: 'Lead Score Changed', label: 'Lead Score Changed', entityType: 'Lead', category: 'Leads' },
    { key: 'Customer Becomes At Risk', label: 'Customer Becomes At Risk', entityType: 'Customer', category: 'Retention' },
    { key: 'Customer Becomes Critical', label: 'Customer Health Critical', entityType: 'Customer', category: 'Retention' },
    { key: 'Ticket Created', label: 'Ticket Created', entityType: 'Ticket', category: 'Support' },
    { key: 'Ticket Priority Changed', label: 'Ticket Priority Changed', entityType: 'Ticket', category: 'Support' },
    { key: 'Ticket Assigned', label: 'Ticket Assigned', entityType: 'Ticket', category: 'Support' },
    { key: 'Ticket SLA At Risk', label: 'Ticket SLA At Risk', entityType: 'Ticket', category: 'Support' },
    { key: 'Ticket SLA Breached', label: 'Ticket SLA Breached', entityType: 'Ticket', category: 'Support' },
    { key: 'Ticket Resolved', label: 'Ticket Resolved', entityType: 'Ticket', category: 'Support' },
    { key: 'Ticket Closed', label: 'Ticket Closed', entityType: 'Ticket', category: 'Support' },
    { key: 'Customer Replied', label: 'Customer Replied to Ticket', entityType: 'Ticket', category: 'Support' },
    { key: 'Proposal Sent', label: 'Proposal Sent', entityType: 'Document', category: 'Sales' },
    { key: 'Customer Payment Received', label: 'Customer Payment Received', entityType: 'Document', category: 'Finance' },
  ],
  actions: [
    { key: 'Send Direct Marketing Email', label: 'Send Marketing Email', category: 'Marketing', available: true },
    { key: 'Enroll in Marketing Campaign', label: 'Enroll in Marketing Campaign', category: 'Marketing', available: true },
    { key: 'Create Task', label: 'Create Follow-Up Task', category: 'Tasks', available: true },
    { key: 'Create Retention Task', label: 'Create Retention Task', category: 'Tasks', available: true },
    { key: 'Create Ticket', label: 'Create Support Ticket', category: 'Support', available: true },
    { key: 'Assign Ticket', label: 'Assign Ticket', category: 'Support', available: true },
    { key: 'Change Priority', label: 'Change Priority', category: 'Support', available: true },
    { key: 'Change Ticket Status', label: 'Change Ticket Status', category: 'Support', available: true },
    { key: 'Add Internal Note', label: 'Add Internal Note', category: 'Support', available: true },
    { key: 'Notify Workspace User', label: 'Notify Workspace User', category: 'Notifications', available: true },
    { key: 'Notify Account Owner', label: 'Notify Account Owner', category: 'Notifications', available: true },
    { key: 'Notify Manager', label: 'Notify Manager', category: 'Notifications', available: true },
  ],
  integrations: [
    { name: 'Email Engine', status: 'Available', details: 'Workspace identity configured' },
    { name: 'Google Drive', status: 'Available', details: 'Connected & active' },
    { name: 'Marketing Engine', status: 'Available', details: 'Active campaign engine' },
    { name: 'Support Desk & Omnichannel Engine', status: 'Available', details: 'Unified Support Operating System active' },
    { name: 'WhatsApp', status: 'Unavailable', details: 'WhatsApp API integration is not connected to this workspace.' },
    { name: 'SMS Gateway', status: 'Unavailable', details: 'No SMS provider gateway configured for this workspace.' },
  ],
};

const getCapabilityRegistry = async (req, res) => {
  res.json({ success: true, data: CAPABILITY_REGISTRY });
};

const parseWorkflowIntent = async (req, res) => {
  try {
    const { prompt } = req.body;
    if (!prompt || typeof prompt !== 'string') {
      return res.status(400).json({ success: false, error: 'Please provide a natural language prompt.' });
    }

    const text = prompt.toLowerCase();
    const result = {
      rawPrompt: prompt,
      trigger: {
        key: 'Lead Stage Changed',
        label: 'Lead Stage Changed',
        stage: 'Interested',
      },
      steps: [],
      unsupportedActions: [],
      canActivate: true,
      suggestedName: '',
    };

    // 1. Identify Trigger
    if (text.includes('customer becomes at risk') || text.includes('at risk')) {
      result.trigger = { key: 'Customer Becomes At Risk', label: 'Customer Becomes At Risk', stage: 'At Risk' };
      result.suggestedName = 'Automated Customer Retention Protocol';
    } else if (text.includes('lead created') || text.includes('new lead')) {
      result.trigger = { key: 'Lead Created', label: 'Lead Created', stage: 'New' };
      result.suggestedName = 'New Lead Onboarding Flow';
    } else if (text.includes('proposal sent') || text.includes('quote sent')) {
      result.trigger = { key: 'Proposal Sent', label: 'Proposal Sent', stage: 'Proposal' };
      result.suggestedName = 'Proposal Follow-Up Automation';
    } else if (text.includes('ticket created') || text.includes('support ticket')) {
      result.trigger = { key: 'Ticket Created', label: 'Ticket Created', stage: 'Open' };
      result.suggestedName = 'Support Escalation Protocol';
    } else {
      let detectedStage = 'Interested';
      if (text.includes('qualified')) detectedStage = 'Qualified';
      else if (text.includes('closed won') || text.includes('won')) detectedStage = 'Closed Won';
      else if (text.includes('contacted')) detectedStage = 'Contacted';

      result.trigger = { key: 'Lead Stage Changed', label: `Lead Stage Changed -> ${detectedStage}`, stage: detectedStage };
      result.suggestedName = `Lead ${detectedStage} Follow-Up Protocol`;
    }

    // 2. Identify Actions
    if (text.includes('email') || text.includes('send them an email') || text.includes('mail')) {
      result.steps.push({
        type: 'Action',
        config: {
          actionType: 'Send Direct Marketing Email',
          emailSubject: `Special Follow-up regarding ${result.trigger.stage}`,
          emailBody: `<p>Hi there,</p><p>Thank you for connecting with us! We wanted to share an update regarding your account.</p>`,
        },
        label: 'Send Marketing Email',
      });
    }

    // Check for unsupported channels (WhatsApp, SMS, etc.)
    if (text.includes('whatsapp') || text.includes('whats app')) {
      result.unsupportedActions.push({
        requested: 'WhatsApp Message',
        reason: 'WhatsApp API integration is not currently connected to this workspace.',
        alternatives: ['Send Marketing Email', 'Create Task', 'Notify Account Owner'],
      });
      result.canActivate = false;
    }
    if (text.includes('sms') || text.includes('text message')) {
      result.unsupportedActions.push({
        requested: 'SMS Message',
        reason: 'No SMS provider gateway configured for this workspace.',
        alternatives: ['Send Marketing Email', 'Create Task', 'Notify Account Owner'],
      });
      result.canActivate = false;
    }

    // Task creation action
    if (text.includes('task') || text.includes('follow-up') || text.includes('reminder')) {
      let delayDays = 2;
      const dayMatch = text.match(/(\d+)\s*day/);
      if (dayMatch && dayMatch[1]) delayDays = parseInt(dayMatch[1], 10);

      result.steps.push({
        type: 'Delay',
        config: {
          delayDuration: delayDays,
          delayUnit: 'Days',
        },
        label: `Wait ${delayDays} Days`,
      });

      result.steps.push({
        type: 'Action',
        config: {
          actionType: 'Create Task',
          taskTitle: `Follow-up with contact regarding ${result.trigger.stage} status`,
          taskPriority: 'High',
        },
        label: 'Create Follow-Up Task',
      });
    }

    // Fallback if no actions specified
    if (result.steps.length === 0 && result.unsupportedActions.length === 0) {
      result.steps.push({
        type: 'Action',
        config: {
          actionType: 'Send Direct Marketing Email',
          emailSubject: `Update regarding ${result.trigger.stage}`,
          emailBody: `<p>Hi there,</p><p>We wanted to follow up with key information regarding your account.</p>`,
        },
        label: 'Send Marketing Email',
      });
    }

    res.json({ success: true, data: result });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

module.exports = {
  getWorkflows,
  createWorkflow,
  updateWorkflow,
  deleteWorkflow,
  getWorkflowLogs,
  triggerWorkflowEvents,
  getCapabilityRegistry,
  parseWorkflowIntent,
};
