const Workflow = require('../models/Workflow');
const WorkflowLog = require('../models/WorkflowLog');
const Task = require('../models/Task');
const Lead = require('../models/Lead');
const Customer = require('../models/Customer');
const Ticket = require('../models/Ticket');
const { getTenantFilter, getTenantId } = require('../utils/tenantScope');

// Helper to simulate workflow step execution
const executeWorkflowStep = async (step, entityType, entityId, tenantId) => {
  const { type, config } = step;
  const execution = { stepType: type, actionType: config.actionType, success: true, error: null };

  try {
    if (type === 'Delay') {
      console.log(`Delaying workflow step for ${config.delayDuration} ${config.delayUnit}`);
    } else if (type === 'Condition') {
      let entity;
      if (entityType === 'Lead') entity = await Lead.findOne({ _id: entityId, tenant: tenantId });
      else if (entityType === 'Customer') entity = await Customer.findOne({ _id: entityId, tenant: tenantId });
      else if (entityType === 'Ticket') entity = await Ticket.findOne({ _id: entityId, tenant: tenantId });

      if (!entity) {
        throw new Error(`${entityType} entity not found for condition evaluation`);
      }

      const fieldValue = entity[config.conditionField];
      const matchValue = config.conditionValue;
      let matched = false;

      switch (config.conditionOperator) {
        case 'equals':
          matched = String(fieldValue) === String(matchValue);
          break;
        case 'not_equals':
          matched = String(fieldValue) !== String(matchValue);
          break;
        case 'contains':
          matched = String(fieldValue).toLowerCase().includes(String(matchValue).toLowerCase());
          break;
        default:
          matched = false;
      }

      if (!matched) {
        execution.success = false;
        execution.error = `Condition field '${config.conditionField}' [${fieldValue}] does not match [${matchValue}]`;
      }
    } else if (type === 'Action') {
      switch (config.actionType) {
        case 'Create Task':
          await Task.create({
            title: config.taskTitle || 'Workflow Automated Task',
            description: `Auto-generated by workflow execution for ${entityType} [${entityId}]`,
            priority: config.taskPriority || 'Medium',
            status: 'Pending',
            tenant: tenantId,
          });
          break;

        case 'Send Email':
        case 'Send SMS':
        case 'Send WhatsApp Message':
          console.log(`[Workflow Outbound] Sending ${config.actionType} to entity: ${entityId}`);
          break;

        case 'Create Ticket':
          await Ticket.create({
            title: 'Automated Alert Ticket',
            description: `Generated automatically via workflow rule. Entity: ${entityType} (${entityId})`,
            priority: 'Medium',
            status: 'Open',
            customer: entityType === 'Customer' ? entityId : undefined,
            tenant: tenantId,
          });
          break;

        default:
          console.log(`Mock executing action: ${config.actionType}`);
      }
    }
  } catch (err) {
    execution.success = false;
    execution.error = err.message;
  }

  return execution;
};

// Execute workflow triggers
const triggerWorkflowEvents = async (triggerName, entityType, entityId, tenantId) => {
  try {
    const workflows = await Workflow.find({ trigger: triggerName, isActive: true, tenant: tenantId });
    for (const workflow of workflows) {
      const log = await WorkflowLog.create({
        workflow: workflow._id,
        entityType,
        entityId,
        status: 'in_progress',
        executedSteps: [],
        tenant: tenantId,
      });

      let allPassed = true;
      const stepResults = [];

      for (let i = 0; i < workflow.steps.length; i++) {
        const step = workflow.steps[i];
        const res = await executeWorkflowStep(step, entityType, entityId, tenantId);
        res.stepIndex = i;
        stepResults.push(res);

        if (!res.success && step.type === 'Condition') {
          allPassed = false;
          break;
        }
      }

      log.executedSteps = stepResults;
      log.status = allPassed ? 'success' : 'failed';
      if (!allPassed) {
        log.errorDetails = stepResults[stepResults.length - 1].error || 'Workflow execution aborted at condition split';
      }
      await log.save();
    }
  } catch (err) {
    console.error('Workflow trigger err:', err.message);
  }
};

const getWorkflows = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const workflows = await Workflow.find(tenantFilter).sort({ createdAt: -1 });
    res.json({ success: true, count: workflows.length, data: workflows });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const createWorkflow = async (req, res) => {
  try {
    const tenantId = getTenantId(req);
    const { name, trigger, steps } = req.body;
    const workflow = await Workflow.create({
      name,
      trigger,
      steps,
      tenant: tenantId,
    });
    res.status(201).json({ success: true, data: workflow });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const updateWorkflow = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const updateData = { ...req.body };
    delete updateData.tenant;

    const workflow = await Workflow.findOneAndUpdate(
      { _id: req.params.id, ...tenantFilter },
      updateData,
      { new: true, runValidators: true }
    );
    if (!workflow) {
      return res.status(404).json({ success: false, error: 'Workflow not found' });
    }
    res.json({ success: true, data: workflow });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const deleteWorkflow = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const workflow = await Workflow.findOneAndDelete({ _id: req.params.id, ...tenantFilter });
    if (!workflow) {
      return res.status(404).json({ success: false, error: 'Workflow not found' });
    }
    res.json({ success: true, message: 'Workflow deleted successfully' });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

const getWorkflowLogs = async (req, res) => {
  try {
    const tenantFilter = getTenantFilter(req);
    const logs = await WorkflowLog.find(tenantFilter)
      .populate('workflow', 'name trigger')
      .sort({ createdAt: -1 });
    res.json({ success: true, count: logs.length, data: logs });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, error: error.message });
  }
};

module.exports = {
  getWorkflows,
  createWorkflow,
  updateWorkflow,
  deleteWorkflow,
  getWorkflowLogs,
  triggerWorkflowEvents,
};
